import type {
  Document,
  Goal,
  Label,
  Note,
  Project,
  Task,
  User,
} from "./types"

export const USERS: User[] = [
  { id: "u1", name: "Maya Chen", initials: "MC", color: "bg-orange-500" },
  { id: "u2", name: "Jordan Park", initials: "JP", color: "bg-blue-500" },
  { id: "u3", name: "Sasha Lopez", initials: "SL", color: "bg-emerald-500" },
  { id: "u4", name: "Theo Nakamura", initials: "TN", color: "bg-rose-500" },
  { id: "u5", name: "Priya Patel", initials: "PP", color: "bg-amber-500" },
  { id: "u6", name: "Omar Khalil", initials: "OK", color: "bg-cyan-500" },
]

export const CURRENT_USER_ID = "u1"

export const PROJECTS: Project[] = [
  { id: "p1", name: "Atlas Redesign", color: "bg-orange-500", emoji: "🛰" },
  { id: "p2", name: "Mobile App v2", color: "bg-blue-500", emoji: "📱" },
  { id: "p3", name: "Marketing Site", color: "bg-emerald-500", emoji: "✨" },
  { id: "p4", name: "Internal Tools", color: "bg-rose-500", emoji: "🔧" },
]

export const LABELS: Label[] = [
  { id: "l1", name: "Frontend", color: "blue" },
  { id: "l2", name: "Backend", color: "emerald" },
  { id: "l3", name: "Design", color: "rose" },
  { id: "l4", name: "Bug", color: "red" },
  { id: "l5", name: "Research", color: "amber" },
  { id: "l6", name: "Docs", color: "cyan" },
]

const iso = (daysFromNow: number, hours = 9) => {
  const d = new Date()
  d.setDate(d.getDate() + daysFromNow)
  d.setHours(hours, 0, 0, 0)
  return d.toISOString()
}

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Design new dashboard layout",
    description:
      "Refresh the analytics dashboard with the new component system. Focus on density and information hierarchy.",
    status: "in-progress",
    priority: "high",
    assigneeId: "u1",
    dueDate: iso(2),
    startDate: iso(-3),
    labels: ["l1", "l3"],
    projectId: "p1",
    dependencyId: undefined,
    comments: [
      {
        id: "c1",
        authorId: "u2",
        body: "Love the direction. Can we explore a denser variant for power users?",
        createdAt: iso(-1, 14),
      },
      {
        id: "c2",
        authorId: "u1",
        body: "Good call — drafting two density options for review tomorrow.",
        createdAt: iso(-1, 16),
      },
    ],
    history: [
      { id: "h1", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-5) },
      { id: "h2", type: "priority", message: "set priority to High", authorId: "u1", createdAt: iso(-4) },
      { id: "h3", type: "status", message: "moved to In Progress", authorId: "u1", createdAt: iso(-3) },
    ],
    references: [
      { id: "r1", title: "Design System v3 spec", url: "https://example.com/ds-v3" },
    ],
    attachments: [
      { id: "a1", name: "dashboard-explorations.fig", size: "12.4 MB", type: "fig" },
    ],
    createdAt: iso(-5),
  },
  {
    id: "t2",
    title: "Fix login redirect loop on Safari",
    description:
      "Customers on Safari 17 hit an infinite redirect after SSO. Suspect SameSite cookie config.",
    status: "in-progress",
    priority: "high",
    assigneeId: "u2",
    dueDate: iso(1),
    startDate: iso(-1),
    labels: ["l4", "l2"],
    projectId: "p2",
    comments: [
      {
        id: "c3",
        authorId: "u3",
        body: "Reproduced on Safari TP. Will share HAR shortly.",
        createdAt: iso(0, 10),
      },
    ],
    history: [
      { id: "h4", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-2) },
      { id: "h5", type: "assignee", message: "assigned Jordan Park", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [
      { id: "a2", name: "safari-har.zip", size: "2.1 MB", type: "zip" },
    ],
    createdAt: iso(-2),
  },
  {
    id: "t3",
    title: "Audit billing edge cases",
    description: "Walk through proration, refunds, and trial-to-paid conversions.",
    status: "backlog",
    priority: "medium",
    assigneeId: "u4",
    dueDate: iso(9),
    startDate: iso(5),
    labels: ["l2", "l5"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h6", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-1),
  },
  {
    id: "t4",
    title: "Write onboarding email sequence",
    description: "5-email sequence covering setup, key features, integrations, and tips.",
    status: "backlog",
    priority: "low",
    assigneeId: "u5",
    dueDate: iso(12),
    startDate: iso(7),
    labels: ["l6"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h7", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-3) },
    ],
    references: [
      { id: "r2", title: "Onboarding research", url: "https://example.com/research" },
    ],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t5",
    title: "Migrate auth to Edge runtime",
    description: "Move session validation to the edge for sub-50ms latency globally.",
    status: "on-hold",
    priority: "medium",
    assigneeId: "u3",
    dueDate: iso(15),
    startDate: iso(2),
    labels: ["l2"],
    projectId: "p2",
    comments: [
      {
        id: "c4",
        authorId: "u3",
        body: "Blocked on infra capacity planning. Resuming next sprint.",
        createdAt: iso(-2, 11),
      },
    ],
    history: [
      { id: "h8", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-7) },
      { id: "h9", type: "status", message: "moved to On Hold", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-7),
  },
  {
    id: "t6",
    title: "Add keyboard shortcuts overlay",
    description: "Cmd/Ctrl+? opens a categorized list of shortcuts with search.",
    status: "in-progress",
    priority: "low",
    assigneeId: "u6",
    dueDate: iso(4),
    startDate: iso(-1),
    labels: ["l1"],
    projectId: "p1",
    comments: [],
    history: [
      { id: "h10", type: "created", message: "created this task", authorId: "u6", createdAt: iso(-4) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-4),
  },
  {
    id: "t7",
    title: "Replace legacy chart library",
    description: "Swap the bespoke charts for the new shared component primitives.",
    status: "done",
    priority: "medium",
    assigneeId: "u1",
    dueDate: iso(-2),
    startDate: iso(-9),
    labels: ["l1"],
    projectId: "p1",
    comments: [
      {
        id: "c5",
        authorId: "u1",
        body: "Shipped in 4.21.0 — perf is up ~40%.",
        createdAt: iso(-2, 17),
      },
    ],
    history: [
      { id: "h11", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-12) },
      { id: "h12", type: "status", message: "marked as Done", authorId: "u1", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-12),
  },
  {
    id: "t8",
    title: "QA sweep of mobile gestures",
    description: "Test pinch-zoom, long-press, and swipe-to-dismiss across iOS and Android.",
    status: "done",
    priority: "high",
    assigneeId: "u4",
    dueDate: iso(-4),
    startDate: iso(-10),
    labels: ["l4"],
    projectId: "p2",
    comments: [],
    history: [
      { id: "h13", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-11) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-11),
  },
  {
    id: "t9",
    title: "Rebrand favicon + meta images",
    description: "Generate new app icons at every required size; update OG images.",
    status: "cancelled",
    priority: "low",
    assigneeId: "u2",
    dueDate: iso(-1),
    startDate: iso(-6),
    labels: ["l3"],
    projectId: "p3",
    comments: [
      {
        id: "c6",
        authorId: "u2",
        body: "Cancelled — folded into the Atlas Redesign rollout.",
        createdAt: iso(-1, 12),
      },
    ],
    history: [
      { id: "h14", type: "created", message: "created this task", authorId: "u2", createdAt: iso(-6) },
      { id: "h15", type: "status", message: "cancelled this task", authorId: "u2", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-6),
  },
  {
    id: "t10",
    title: "Spike: Realtime presence",
    description: "Prototype WebSocket-based presence for collaborative editing.",
    status: "backlog",
    priority: "medium",
    assigneeId: "u6",
    dueDate: iso(20),
    startDate: iso(14),
    labels: ["l5", "l2"],
    projectId: "p2",
    comments: [],
    history: [
      { id: "h16", type: "created", message: "created this task", authorId: "u6", createdAt: iso(0) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(0),
  },
  {
    id: "t11",
    title: "Update pricing page copy",
    description: "Reflect the new tier structure and feature comparisons.",
    status: "in-progress",
    priority: "medium",
    assigneeId: "u5",
    dueDate: iso(3),
    startDate: iso(-2),
    labels: ["l6", "l3"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h17", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-3) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t12",
    title: "Investigate flaky integration tests",
    description: "Identify which tests are timing-sensitive vs. order-dependent.",
    status: "on-hold",
    priority: "high",
    assigneeId: "u3",
    dueDate: iso(7),
    startDate: iso(0),
    labels: ["l4", "l2"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h18", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-2),
  },
  {
    id: "t13",
    title: "Document API rate limits",
    description: "Public-facing docs for the v2 API limits and burst behavior.",
    status: "backlog",
    priority: "low",
    assigneeId: "u1",
    dueDate: iso(11),
    startDate: iso(8),
    labels: ["l6"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h19", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-1),
  },
  {
    id: "t14",
    title: "Empty states pass",
    description: "Add illustrations and helpful copy to all empty states across the app.",
    status: "in-progress",
    priority: "low",
    assigneeId: "u4",
    dueDate: iso(6),
    startDate: iso(-1),
    labels: ["l3", "l1"],
    projectId: "p1",
    comments: [],
    history: [
      { id: "h20", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-3) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t15",
    title: "Customer interview synthesis",
    description: "Cluster themes from the last 12 customer interviews.",
    status: "done",
    priority: "medium",
    assigneeId: "u5",
    dueDate: iso(-3),
    startDate: iso(-8),
    labels: ["l5"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h21", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-8) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-8),
  },
]

export const NOTES: Note[] = [
  {
    id: "n1",
    title: "Atlas redesign — kickoff notes",
    body: "Goals: improve information density, ship the new component primitives, and reduce cold-start render time by 30%. Stakeholders: design, platform, growth. Risks: legacy chart lib, mobile gesture parity.",
    updatedAt: iso(-1, 15),
  },
  {
    id: "n2",
    title: "Q3 OKRs",
    body: "1) Activation rate ≥ 55%. 2) p95 page load < 1.2s globally. 3) Ship realtime presence (beta). 4) Reduce paid-trial drop-off by 20%.",
    updatedAt: iso(-3, 10),
  },
  {
    id: "n3",
    title: "Customer interview — Helio Labs",
    body: "Helio uses our API for nightly batch jobs. Pain points: rate limit observability, lack of webhooks for partial failures. Wants: SDK in Go, finer-grained API keys.",
    updatedAt: iso(-5, 12),
  },
  {
    id: "n4",
    title: "Eng standup template",
    body: "What I shipped • What I'm shipping • Where I'm stuck • Anything cross-team.",
    updatedAt: iso(-9, 9),
  },
]

export const GOALS: Goal[] = [
  {
    id: "g1",
    title: "Reduce p95 page load to < 1.2s",
    description: "Across all surfaces, on production traffic.",
    progress: 72,
    status: "on-track",
    dueDate: iso(45),
    ownerId: "u1",
  },
  {
    id: "g2",
    title: "Ship realtime presence (beta)",
    description: "Cursors and selection in shared documents.",
    progress: 25,
    status: "at-risk",
    dueDate: iso(30),
    ownerId: "u6",
  },
  {
    id: "g3",
    title: "Activation rate ≥ 55%",
    description: "% of new workspaces active within 7 days.",
    progress: 88,
    status: "on-track",
    dueDate: iso(60),
    ownerId: "u5",
  },
  {
    id: "g4",
    title: "Cut paid-trial drop-off by 20%",
    description: "Improve paywall, billing UX, and recovery flows.",
    progress: 12,
    status: "off-track",
    dueDate: iso(50),
    ownerId: "u2",
  },
  {
    id: "g5",
    title: "Migrate auth to edge runtime",
    description: "Sub-50ms session validation worldwide.",
    progress: 100,
    status: "completed",
    dueDate: iso(-2),
    ownerId: "u3",
  },
]

export const DOCUMENTS: Document[] = [
  { id: "d1", name: "Brand Guidelines.pdf", type: "pdf", size: "8.2 MB", updatedAt: iso(-1), ownerId: "u1" },
  { id: "d2", name: "Q3 Roadmap.doc", type: "doc", size: "412 KB", updatedAt: iso(-2), ownerId: "u2" },
  { id: "d3", name: "User Research.sheet", type: "sheet", size: "1.1 MB", updatedAt: iso(-3), ownerId: "u5" },
  { id: "d4", name: "Onboarding Hero.png", type: "image", size: "2.4 MB", updatedAt: iso(-4), ownerId: "u4" },
  { id: "d5", name: "Demo Walkthrough.mp4", type: "video", size: "84.6 MB", updatedAt: iso(-5), ownerId: "u6" },
  { id: "d6", name: "Press Kit.zip", type: "zip", size: "32.1 MB", updatedAt: iso(-7), ownerId: "u2" },
  { id: "d7", name: "Pricing v3.sheet", type: "sheet", size: "260 KB", updatedAt: iso(-9), ownerId: "u5" },
  { id: "d8", name: "Architecture Diagram.pdf", type: "pdf", size: "1.8 MB", updatedAt: iso(-12), ownerId: "u3" },
]
