import type {
  ChatChannel,
  ChatMessage,
  Document,
  Goal,
  Label,
  Note,
  PresenceStatus,
  Project,
  Task,
  User,
} from "./types"

export const USERS: User[] = [
  { id: "u1", name: "Maya Chen", initials: "MC", color: "bg-orange-500" },
  { id: "u2", name: "Jordan Park", initials: "JP", color: "bg-blue-500" },
  { id: "u3", name: "Sasha Lopez", initials: "SL", color: "bg-emerald-500" },
  { id: "u4", name: "Theo Nakamura", initials: "TN", color: "bg-rose-500" },
  { id: "u5", name: "Priya Patel", initials: "PP", color: "bg-amber-500" },
  { id: "u6", name: "Omar Khalil", initials: "OK", color: "bg-cyan-500" },
]

export const CURRENT_USER_ID = "u1"

export const PROJECTS: Project[] = [
  { id: "p1", name: "Atlas Redesign", color: "bg-orange-500", emoji: "🛰" },
  { id: "p2", name: "Mobile App v2", color: "bg-blue-500", emoji: "📱" },
  { id: "p3", name: "Marketing Site", color: "bg-emerald-500", emoji: "✨" },
  { id: "p4", name: "Internal Tools", color: "bg-rose-500", emoji: "🔧" },
]

export const LABELS: Label[] = [
  { id: "l1", name: "Frontend", color: "blue" },
  { id: "l2", name: "Backend", color: "emerald" },
  { id: "l3", name: "Design", color: "rose" },
  { id: "l4", name: "Bug", color: "red" },
  { id: "l5", name: "Research", color: "amber" },
  { id: "l6", name: "Docs", color: "cyan" },
]

const iso = (daysFromNow: number, hours = 9) => {
  const d = new Date()
  d.setDate(d.getDate() + daysFromNow)
  d.setHours(hours, 0, 0, 0)
  return d.toISOString()
}

export const TASKS: Task[] = [
  {
    id: "t1",
    title: "Design new dashboard layout",
    description:
      "Refresh the analytics dashboard with the new component system. Focus on density and information hierarchy.",
    status: "in-progress",
    priority: "high",
    assigneeId: "u1",
    dueDate: iso(2),
    startDate: iso(-3),
    labels: ["l1", "l3"],
    projectId: "p1",
    dependencyId: undefined,
    comments: [
      {
        id: "c1",
        authorId: "u2",
        body: "Love the direction. Can we explore a denser variant for power users?",
        createdAt: iso(-1, 14),
      },
      {
        id: "c2",
        authorId: "u1",
        body: "Good call — drafting two density options for review tomorrow.",
        createdAt: iso(-1, 16),
      },
    ],
    history: [
      { id: "h1", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-5) },
      { id: "h2", type: "priority", message: "set priority to High", authorId: "u1", createdAt: iso(-4) },
      { id: "h3", type: "status", message: "moved to In Progress", authorId: "u1", createdAt: iso(-3) },
    ],
    references: [
      { id: "r1", title: "Design System v3 spec", url: "https://example.com/ds-v3" },
    ],
    attachments: [
      { id: "a1", name: "dashboard-explorations.fig", size: "12.4 MB", type: "fig" },
    ],
    createdAt: iso(-5),
  },
  {
    id: "t2",
    title: "Fix login redirect loop on Safari",
    description:
      "Customers on Safari 17 hit an infinite redirect after SSO. Suspect SameSite cookie config.",
    status: "in-progress",
    priority: "high",
    assigneeId: "u2",
    dueDate: iso(1),
    startDate: iso(-1),
    labels: ["l4", "l2"],
    projectId: "p2",
    comments: [
      {
        id: "c3",
        authorId: "u3",
        body: "Reproduced on Safari TP. Will share HAR shortly.",
        createdAt: iso(0, 10),
      },
    ],
    history: [
      { id: "h4", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-2) },
      { id: "h5", type: "assignee", message: "assigned Jordan Park", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [
      { id: "a2", name: "safari-har.zip", size: "2.1 MB", type: "zip" },
    ],
    createdAt: iso(-2),
  },
  {
    id: "t3",
    title: "Audit billing edge cases",
    description: "Walk through proration, refunds, and trial-to-paid conversions.",
    status: "backlog",
    priority: "medium",
    assigneeId: "u4",
    dueDate: iso(9),
    startDate: iso(5),
    labels: ["l2", "l5"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h6", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-1),
  },
  {
    id: "t4",
    title: "Write onboarding email sequence",
    description: "5-email sequence covering setup, key features, integrations, and tips.",
    status: "backlog",
    priority: "low",
    assigneeId: "u5",
    dueDate: iso(12),
    startDate: iso(7),
    labels: ["l6"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h7", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-3) },
    ],
    references: [
      { id: "r2", title: "Onboarding research", url: "https://example.com/research" },
    ],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t5",
    title: "Migrate auth to Edge runtime",
    description: "Move session validation to the edge for sub-50ms latency globally.",
    status: "on-hold",
    priority: "medium",
    assigneeId: "u3",
    dueDate: iso(15),
    startDate: iso(2),
    labels: ["l2"],
    projectId: "p2",
    comments: [
      {
        id: "c4",
        authorId: "u3",
        body: "Blocked on infra capacity planning. Resuming next sprint.",
        createdAt: iso(-2, 11),
      },
    ],
    history: [
      { id: "h8", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-7) },
      { id: "h9", type: "status", message: "moved to On Hold", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-7),
  },
  {
    id: "t6",
    title: "Add keyboard shortcuts overlay",
    description: "Cmd/Ctrl+? opens a categorized list of shortcuts with search.",
    status: "in-progress",
    priority: "low",
    assigneeId: "u6",
    dueDate: iso(4),
    startDate: iso(-1),
    labels: ["l1"],
    projectId: "p1",
    comments: [],
    history: [
      { id: "h10", type: "created", message: "created this task", authorId: "u6", createdAt: iso(-4) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-4),
  },
  {
    id: "t7",
    title: "Replace legacy chart library",
    description: "Swap the bespoke charts for the new shared component primitives.",
    status: "done",
    priority: "medium",
    assigneeId: "u1",
    dueDate: iso(-2),
    startDate: iso(-9),
    labels: ["l1"],
    projectId: "p1",
    comments: [
      {
        id: "c5",
        authorId: "u1",
        body: "Shipped in 4.21.0 — perf is up ~40%.",
        createdAt: iso(-2, 17),
      },
    ],
    history: [
      { id: "h11", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-12) },
      { id: "h12", type: "status", message: "marked as Done", authorId: "u1", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-12),
  },
  {
    id: "t8",
    title: "QA sweep of mobile gestures",
    description: "Test pinch-zoom, long-press, and swipe-to-dismiss across iOS and Android.",
    status: "done",
    priority: "high",
    assigneeId: "u4",
    dueDate: iso(-4),
    startDate: iso(-10),
    labels: ["l4"],
    projectId: "p2",
    comments: [],
    history: [
      { id: "h13", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-11) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-11),
  },
  {
    id: "t9",
    title: "Rebrand favicon + meta images",
    description: "Generate new app icons at every required size; update OG images.",
    status: "cancelled",
    priority: "low",
    assigneeId: "u2",
    dueDate: iso(-1),
    startDate: iso(-6),
    labels: ["l3"],
    projectId: "p3",
    comments: [
      {
        id: "c6",
        authorId: "u2",
        body: "Cancelled — folded into the Atlas Redesign rollout.",
        createdAt: iso(-1, 12),
      },
    ],
    history: [
      { id: "h14", type: "created", message: "created this task", authorId: "u2", createdAt: iso(-6) },
      { id: "h15", type: "status", message: "cancelled this task", authorId: "u2", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-6),
  },
  {
    id: "t10",
    title: "Spike: Realtime presence",
    description: "Prototype WebSocket-based presence for collaborative editing.",
    status: "backlog",
    priority: "medium",
    assigneeId: "u6",
    dueDate: iso(20),
    startDate: iso(14),
    labels: ["l5", "l2"],
    projectId: "p2",
    comments: [],
    history: [
      { id: "h16", type: "created", message: "created this task", authorId: "u6", createdAt: iso(0) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(0),
  },
  {
    id: "t11",
    title: "Update pricing page copy",
    description: "Reflect the new tier structure and feature comparisons.",
    status: "in-progress",
    priority: "medium",
    assigneeId: "u5",
    dueDate: iso(3),
    startDate: iso(-2),
    labels: ["l6", "l3"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h17", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-3) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t12",
    title: "Investigate flaky integration tests",
    description: "Identify which tests are timing-sensitive vs. order-dependent.",
    status: "on-hold",
    priority: "high",
    assigneeId: "u3",
    dueDate: iso(7),
    startDate: iso(0),
    labels: ["l4", "l2"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h18", type: "created", message: "created this task", authorId: "u3", createdAt: iso(-2) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-2),
  },
  {
    id: "t13",
    title: "Document API rate limits",
    description: "Public-facing docs for the v2 API limits and burst behavior.",
    status: "backlog",
    priority: "low",
    assigneeId: "u1",
    dueDate: iso(11),
    startDate: iso(8),
    labels: ["l6"],
    projectId: "p4",
    comments: [],
    history: [
      { id: "h19", type: "created", message: "created this task", authorId: "u1", createdAt: iso(-1) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-1),
  },
  {
    id: "t14",
    title: "Empty states pass",
    description: "Add illustrations and helpful copy to all empty states across the app.",
    status: "in-progress",
    priority: "low",
    assigneeId: "u4",
    dueDate: iso(6),
    startDate: iso(-1),
    labels: ["l3", "l1"],
    projectId: "p1",
    comments: [],
    history: [
      { id: "h20", type: "created", message: "created this task", authorId: "u4", createdAt: iso(-3) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-3),
  },
  {
    id: "t15",
    title: "Customer interview synthesis",
    description: "Cluster themes from the last 12 customer interviews.",
    status: "done",
    priority: "medium",
    assigneeId: "u5",
    dueDate: iso(-3),
    startDate: iso(-8),
    labels: ["l5"],
    projectId: "p3",
    comments: [],
    history: [
      { id: "h21", type: "created", message: "created this task", authorId: "u5", createdAt: iso(-8) },
    ],
    references: [],
    attachments: [],
    createdAt: iso(-8),
  },
]

export const NOTES: Note[] = [
  {
    id: "n1",
    title: "Atlas redesign — kickoff notes",
    body: "Goals: improve information density, ship the new component primitives, and reduce cold-start render time by 30%. Stakeholders: design, platform, growth. Risks: legacy chart lib, mobile gesture parity.",
    updatedAt: iso(-1, 15),
  },
  {
    id: "n2",
    title: "Q3 OKRs",
    body: "1) Activation rate ≥ 55%. 2) p95 page load < 1.2s globally. 3) Ship realtime presence (beta). 4) Reduce paid-trial drop-off by 20%.",
    updatedAt: iso(-3, 10),
  },
  {
    id: "n3",
    title: "Customer interview — Helio Labs",
    body: "Helio uses our API for nightly batch jobs. Pain points: rate limit observability, lack of webhooks for partial failures. Wants: SDK in Go, finer-grained API keys.",
    updatedAt: iso(-5, 12),
  },
  {
    id: "n4",
    title: "Eng standup template",
    body: "What I shipped • What I'm shipping • Where I'm stuck • Anything cross-team.",
    updatedAt: iso(-9, 9),
  },
]

export const GOALS: Goal[] = [
  {
    id: "g1",
    title: "Reduce p95 page load to < 1.2s",
    description: "Across all surfaces, on production traffic.",
    progress: 72,
    status: "on-track",
    dueDate: iso(45),
    ownerId: "u1",
  },
  {
    id: "g2",
    title: "Ship realtime presence (beta)",
    description: "Cursors and selection in shared documents.",
    progress: 25,
    status: "at-risk",
    dueDate: iso(30),
    ownerId: "u6",
  },
  {
    id: "g3",
    title: "Activation rate ≥ 55%",
    description: "% of new workspaces active within 7 days.",
    progress: 88,
    status: "on-track",
    dueDate: iso(60),
    ownerId: "u5",
  },
  {
    id: "g4",
    title: "Cut paid-trial drop-off by 20%",
    description: "Improve paywall, billing UX, and recovery flows.",
    progress: 12,
    status: "off-track",
    dueDate: iso(50),
    ownerId: "u2",
  },
  {
    id: "g5",
    title: "Migrate auth to edge runtime",
    description: "Sub-50ms session validation worldwide.",
    progress: 100,
    status: "completed",
    dueDate: iso(-2),
    ownerId: "u3",
  },
]

export const USER_PRESENCE: Record<string, PresenceStatus> = {
  u1: "online",
  u2: "online",
  u3: "away",
  u4: "online",
  u5: "dnd",
  u6: "offline",
}

export const CHAT_CHANNELS: ChatChannel[] = [
  {
    id: "ch-general",
    type: "channel",
    name: "general",
    description: "Company-wide announcements and chatter.",
    memberIds: ["u1", "u2", "u3", "u4", "u5", "u6"],
    unreadCount: 0,
  },
  {
    id: "ch-design",
    type: "channel",
    name: "design",
    description: "Atlas redesign, design system, and visual exploration.",
    memberIds: ["u1", "u2", "u4", "u5"],
    unreadCount: 3,
  },
  {
    id: "ch-engineering",
    type: "channel",
    name: "engineering",
    description: "Engineering discussion, code reviews, infra.",
    memberIds: ["u1", "u2", "u3", "u6"],
    unreadCount: 0,
  },
  {
    id: "ch-random",
    type: "channel",
    name: "random",
    description: "Off-topic — memes, music, weekend plans.",
    memberIds: ["u1", "u2", "u3", "u4", "u5", "u6"],
    unreadCount: 12,
  },
  {
    id: "ch-announcements",
    type: "channel",
    name: "announcements",
    description: "Read-only updates from leadership.",
    memberIds: ["u1", "u2", "u3", "u4", "u5", "u6"],
    unreadCount: 0,
  },
  {
    id: "dm-u2",
    type: "dm",
    name: "Jordan Park",
    memberIds: ["u1", "u2"],
    unreadCount: 2,
  },
  {
    id: "dm-u3",
    type: "dm",
    name: "Sasha Lopez",
    memberIds: ["u1", "u3"],
    unreadCount: 0,
  },
  {
    id: "dm-u5",
    type: "dm",
    name: "Priya Patel",
    memberIds: ["u1", "u5"],
    unreadCount: 0,
  },
  {
    id: "dm-u6",
    type: "dm",
    name: "Omar Khalil",
    memberIds: ["u1", "u6"],
    unreadCount: 0,
  },
]

const minutesAgo = (m: number) => {
  const d = new Date()
  d.setMinutes(d.getMinutes() - m)
  return d.toISOString()
}

const hoursAgo = (h: number, m = 0) => {
  const d = new Date()
  d.setHours(d.getHours() - h, d.getMinutes() - m, 0, 0)
  return d.toISOString()
}

const daysAgo = (days: number, hour = 10, minute = 0) => {
  const d = new Date()
  d.setDate(d.getDate() - days)
  d.setHours(hour, minute, 0, 0)
  return d.toISOString()
}

export const CHAT_MESSAGES: ChatMessage[] = [
  // ===== #general =====
  {
    id: "m-g-1",
    channelId: "ch-general",
    authorId: "u4",
    body: "Morning team. Coffee machine on 3 is making a noise that can only be described as 'concerned'.",
    createdAt: daysAgo(1, 9, 12),
    reactions: [{ emoji: "☕", userIds: ["u1", "u2", "u5"] }],
  },
  {
    id: "m-g-2",
    channelId: "ch-general",
    authorId: "u2",
    body: "Confirmed. I am also concerned.",
    createdAt: daysAgo(1, 9, 14),
    reactions: [{ emoji: "😂", userIds: ["u4", "u1"] }],
  },
  {
    id: "m-g-3",
    channelId: "ch-general",
    authorId: "u5",
    body: "Reminder: All-hands at 2pm. Maya is showing off the new dashboard.",
    createdAt: daysAgo(1, 11, 30),
    reactions: [],
  },
  {
    id: "m-g-4",
    channelId: "ch-general",
    authorId: "u1",
    body: "Slides are 90% there. Anyone want to dry-run with me at 1:30?",
    createdAt: daysAgo(1, 11, 32),
    reactions: [{ emoji: "🙋", userIds: ["u2"] }],
  },
  {
    id: "m-g-5",
    channelId: "ch-general",
    authorId: "u2",
    body: "Me. I'll bring snacks.",
    createdAt: daysAgo(1, 11, 33),
    reactions: [{ emoji: "🍪", userIds: ["u1", "u4", "u5"] }],
  },
  {
    id: "m-g-6",
    channelId: "ch-general",
    authorId: "u3",
    body: "Heads up — pushing a small auth fix to staging in ~10. Should be transparent but ping me if anything looks off.",
    createdAt: hoursAgo(4),
    reactions: [{ emoji: "👀", userIds: ["u6"] }],
  },
  {
    id: "m-g-7",
    channelId: "ch-general",
    authorId: "u6",
    body: "Watching.",
    createdAt: hoursAgo(3, 55),
    reactions: [],
  },
  {
    id: "m-g-8",
    channelId: "ch-general",
    authorId: "u3",
    body: "All green. Thanks!",
    createdAt: hoursAgo(3, 30),
    reactions: [{ emoji: "✅", userIds: ["u1", "u2", "u6"] }],
  },

  // ===== #design =====
  {
    id: "m-d-1",
    channelId: "ch-design",
    authorId: "u1",
    body: "Posted two density variants of the dashboard in Figma. Comfortable vs Compact. Curious which feels right at a glance.",
    createdAt: daysAgo(1, 14, 5),
    reactions: [{ emoji: "🔥", userIds: ["u2", "u4"] }],
  },
  {
    id: "m-d-2",
    channelId: "ch-design",
    authorId: "u4",
    body: "Compact is gorgeous but I worry about the secondary metric labels at small sizes. Have you tried bumping them to 12 with a subtle weight increase?",
    createdAt: daysAgo(1, 14, 18),
    reactions: [],
  },
  {
    id: "m-d-3",
    channelId: "ch-design",
    authorId: "u1",
    body: "Good shout. I'll spin a v3 with that tweak tonight.",
    createdAt: daysAgo(1, 14, 22),
    reactions: [{ emoji: "🙏", userIds: ["u4"] }],
  },
  {
    id: "m-d-4",
    channelId: "ch-design",
    authorId: "u2",
    body: "From an eng perspective: compact is fine if the chart legend wraps cleanly under 360px. Otherwise we'll need a fallback.",
    createdAt: daysAgo(1, 14, 40),
    reactions: [],
  },
  {
    id: "m-d-5",
    channelId: "ch-design",
    authorId: "u5",
    body: "Marketing perspective: the comfortable one screenshots better for blog posts and pricing pages. Just FYI.",
    createdAt: hoursAgo(20),
    reactions: [{ emoji: "💯", userIds: ["u1"] }],
  },
  {
    id: "m-d-6",
    channelId: "ch-design",
    authorId: "u1",
    body: "Could we ship Comfortable as default and Compact as a preference? Keeps everyone happy.",
    createdAt: hoursAgo(2),
    reactions: [{ emoji: "👍", userIds: ["u2", "u4", "u5"] }],
  },
  {
    id: "m-d-7",
    channelId: "ch-design",
    authorId: "u4",
    body: "Vote: yes. Ships in 4.22?",
    createdAt: minutesAgo(45),
    reactions: [{ emoji: "🚀", userIds: ["u1"] }],
  },
  {
    id: "m-d-8",
    channelId: "ch-design",
    authorId: "u1",
    body: "Targeting 4.22 if QA cooperates. Will sync in standup.",
    createdAt: minutesAgo(28),
    reactions: [],
  },

  // ===== #engineering =====
  {
    id: "m-e-1",
    channelId: "ch-engineering",
    authorId: "u3",
    body: "Anyone seeing intermittent 502s on the staging cluster? Started about 20 mins ago.",
    createdAt: hoursAgo(8),
    reactions: [],
  },
  {
    id: "m-e-2",
    channelId: "ch-engineering",
    authorId: "u6",
    body: "Yep. Looks like the load balancer healthcheck is too aggressive after the last deploy. Bumping the timeout.",
    createdAt: hoursAgo(7, 50),
    reactions: [{ emoji: "🔧", userIds: ["u3"] }],
  },
  {
    id: "m-e-3",
    channelId: "ch-engineering",
    authorId: "u3",
    body: "Confirmed fixed on my end. Thanks Omar.",
    createdAt: hoursAgo(7, 35),
    reactions: [{ emoji: "🙌", userIds: ["u6"] }],
  },
  {
    id: "m-e-4",
    channelId: "ch-engineering",
    authorId: "u2",
    body: "PR up for the Safari redirect loop. Root cause was exactly the SameSite=Lax thing — sub-domain set was missing the parent. https://github.com/atlas/web/pull/4821",
    createdAt: hoursAgo(5, 12),
    reactions: [{ emoji: "🥳", userIds: ["u1", "u3"] }],
  },
  {
    id: "m-e-5",
    channelId: "ch-engineering",
    authorId: "u1",
    body: "Reviewing now. Will leave comments inline.",
    createdAt: hoursAgo(5, 9),
    reactions: [],
  },
  {
    id: "m-e-6",
    channelId: "ch-engineering",
    authorId: "u3",
    body: "Drive-by: can we add an integration test that boots Safari TP in CI? Would've caught this.",
    createdAt: hoursAgo(4, 55),
    reactions: [{ emoji: "💡", userIds: ["u2", "u6"] }],
  },
  {
    id: "m-e-7",
    channelId: "ch-engineering",
    authorId: "u2",
    body: "Filed a ticket: ATLAS-2391. Will pick up after the redirect fix lands.",
    createdAt: hoursAgo(4, 50),
    reactions: [],
  },
  {
    id: "m-e-8",
    channelId: "ch-engineering",
    authorId: "u6",
    body: "Realtime presence spike progress: cursor positions are flowing through the WS layer. Need to figure out coalescing before this scales past ~50 users.",
    createdAt: minutesAgo(70),
    reactions: [{ emoji: "👀", userIds: ["u1", "u3"] }],
  },
  {
    id: "m-e-9",
    channelId: "ch-engineering",
    authorId: "u1",
    body: "Have you looked at how Linear does it? They throttle to 30hz and it feels great.",
    createdAt: minutesAgo(64),
    reactions: [],
  },
  {
    id: "m-e-10",
    channelId: "ch-engineering",
    authorId: "u6",
    body: "Yeah, leaning that way. Will write up the approach in an RFC tomorrow.",
    createdAt: minutesAgo(60),
    reactions: [{ emoji: "📄", userIds: ["u1"] }],
  },

  // ===== #random =====
  {
    id: "m-r-1",
    channelId: "ch-random",
    authorId: "u5",
    body: "What is everyone listening to while shipping today?",
    createdAt: hoursAgo(6),
    reactions: [],
  },
  {
    id: "m-r-2",
    channelId: "ch-random",
    authorId: "u4",
    body: "Lo-fi beats and the gentle hum of regret.",
    createdAt: hoursAgo(5, 55),
    reactions: [{ emoji: "😂", userIds: ["u1", "u2", "u5", "u3"] }],
  },
  {
    id: "m-r-3",
    channelId: "ch-random",
    authorId: "u3",
    body: "Hans Zimmer's Interstellar score. On loop. For the third week.",
    createdAt: hoursAgo(5, 50),
    reactions: [{ emoji: "🪐", userIds: ["u4"] }],
  },
  {
    id: "m-r-4",
    channelId: "ch-random",
    authorId: "u2",
    body: "Dad rock. Strictly dad rock.",
    createdAt: hoursAgo(5, 45),
    reactions: [{ emoji: "🎸", userIds: ["u5", "u4"] }],
  },
  {
    id: "m-r-5",
    channelId: "ch-random",
    authorId: "u6",
    body: "Silence. Bug fixing requires reverence.",
    createdAt: hoursAgo(2),
    reactions: [{ emoji: "🤫", userIds: ["u1", "u3"] }],
  },
  {
    id: "m-r-6",
    channelId: "ch-random",
    authorId: "u1",
    body: "I made a 4-hour playlist called 'Atlas Redesign' and refuse to take suggestions.",
    createdAt: minutesAgo(120),
    reactions: [{ emoji: "🎧", userIds: ["u4", "u2", "u5"] }],
  },

  // ===== #announcements =====
  {
    id: "m-a-1",
    channelId: "ch-announcements",
    authorId: "u5",
    body: "We crossed **5,000 active workspaces** this week. Huge milestone — thank you everyone for the work going in.",
    createdAt: daysAgo(2, 16, 0),
    reactions: [
      { emoji: "🎉", userIds: ["u1", "u2", "u3", "u4", "u6"] },
      { emoji: "🚀", userIds: ["u1", "u3"] },
    ],
  },
  {
    id: "m-a-2",
    channelId: "ch-announcements",
    authorId: "u5",
    body: "Office will be closed next Monday for the company offsite. Travel details in your inbox.",
    createdAt: daysAgo(1, 17, 30),
    reactions: [{ emoji: "🏝", userIds: ["u4", "u2", "u1", "u6"] }],
  },

  // ===== DM with Jordan (u2) =====
  {
    id: "m-dm2-1",
    channelId: "dm-u2",
    authorId: "u2",
    body: "Hey, did you get a chance to look at the staging build? I want to make sure the Safari fix didn't regress anything.",
    createdAt: hoursAgo(3),
    reactions: [],
  },
  {
    id: "m-dm2-2",
    channelId: "dm-u2",
    authorId: "u1",
    body: "Just clicked through the main flows — looks clean. Login, dashboard, settings all good.",
    createdAt: hoursAgo(2, 50),
    reactions: [{ emoji: "🙌", userIds: ["u2"] }],
  },
  {
    id: "m-dm2-3",
    channelId: "dm-u2",
    authorId: "u2",
    body: "Perfect. Mind giving the PR a quick approval when you have a sec?",
    createdAt: minutesAgo(35),
    reactions: [],
  },
  {
    id: "m-dm2-4",
    channelId: "dm-u2",
    authorId: "u2",
    body: "Also — are you still up for the dry-run at 1:30?",
    createdAt: minutesAgo(8),
    reactions: [],
  },

  // ===== DM with Sasha (u3) =====
  {
    id: "m-dm3-1",
    channelId: "dm-u3",
    authorId: "u1",
    body: "Quick one: what's the timeline looking like on the edge auth migration? Trying to plan around it.",
    createdAt: hoursAgo(20),
    reactions: [],
  },
  {
    id: "m-dm3-2",
    channelId: "dm-u3",
    authorId: "u3",
    body: "Realistically? Two more weeks. Infra capacity planning got us, but we're unblocked now.",
    createdAt: hoursAgo(19, 50),
    reactions: [],
  },
  {
    id: "m-dm3-3",
    channelId: "dm-u3",
    authorId: "u1",
    body: "Got it. I'll plan the dashboard rollout to land after, then.",
    createdAt: hoursAgo(19, 45),
    reactions: [{ emoji: "👍", userIds: ["u3"] }],
  },

  // ===== DM with Priya (u5) =====
  {
    id: "m-dm5-1",
    channelId: "dm-u5",
    authorId: "u5",
    body: "Pricing copy is in the doc. I left two options for the headline — would love your gut reaction.",
    createdAt: hoursAgo(7),
    reactions: [],
  },
  {
    id: "m-dm5-2",
    channelId: "dm-u5",
    authorId: "u1",
    body: "Option B. The verb makes it feel more active.",
    createdAt: hoursAgo(6, 30),
    reactions: [{ emoji: "🎯", userIds: ["u5"] }],
  },

  // ===== DM with Omar (u6) =====
  {
    id: "m-dm6-1",
    channelId: "dm-u6",
    authorId: "u6",
    body: "Sending you the WS coalescing RFC tomorrow morning. Want you in the room when we discuss.",
    createdAt: hoursAgo(1, 30),
    reactions: [],
  },
  {
    id: "m-dm6-2",
    channelId: "dm-u6",
    authorId: "u1",
    body: "Wouldn't miss it.",
    createdAt: hoursAgo(1, 28),
    reactions: [],
  },
]

export const DOCUMENTS: Document[] = [
  { id: "d1", name: "Brand Guidelines.pdf", type: "pdf", size: "8.2 MB", updatedAt: iso(-1), ownerId: "u1" },
  { id: "d2", name: "Q3 Roadmap.doc", type: "doc", size: "412 KB", updatedAt: iso(-2), ownerId: "u2" },
  { id: "d3", name: "User Research.sheet", type: "sheet", size: "1.1 MB", updatedAt: iso(-3), ownerId: "u5" },
  { id: "d4", name: "Onboarding Hero.png", type: "image", size: "2.4 MB", updatedAt: iso(-4), ownerId: "u4" },
  { id: "d5", name: "Demo Walkthrough.mp4", type: "video", size: "84.6 MB", updatedAt: iso(-5), ownerId: "u6" },
  { id: "d6", name: "Press Kit.zip", type: "zip", size: "32.1 MB", updatedAt: iso(-7), ownerId: "u2" },
  { id: "d7", name: "Pricing v3.sheet", type: "sheet", size: "260 KB", updatedAt: iso(-9), ownerId: "u5" },
  { id: "d8", name: "Architecture Diagram.pdf", type: "pdf", size: "1.8 MB", updatedAt: iso(-12), ownerId: "u3" },
]
